// <auto-generated />
using System;
using EquipmentChecklist.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquipmentChecklist.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260325200000_AddTemplateItemDetails")]
    partial class AddTemplateItemDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This designer file references the snapshot — it is intentionally minimal.
            // The snapshot (ApplicationDbContextModelSnapshot.cs) is the canonical model.
        }
    }
}
