-- ════════════════════════════════════════════════════════════════════════════
--  EquipmentChecklist · Full Database Setup (PostgreSQL)
--  Generated from EF Core migrations up to and including:
--      20260520000000_AddIconLibrary
--
--  This script is IDEMPOTENT-ISH:
--    - It uses CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS so
--      running it on a partially-set-up DB won't error, but it will NOT
--      reshape existing tables. For a clean run, drop the schema first
--      (see the optional "RESET" block right below) and then run the rest.
--    - It marks every EF migration as applied at the end, so the app's
--      `dotnet ef database update` will see "no pending migrations"
--      and not try to re-run them.
--
--  Required PostgreSQL version: 13+
--  Run as the owner of the application database.
-- ════════════════════════════════════════════════════════════════════════════

-- ────────────────────────────────────────────────────────────────────────────
-- OPTIONAL · RESET BLOCK  (uncomment ONLY if you want to nuke an existing DB)
-- ────────────────────────────────────────────────────────────────────────────
 DROP TABLE IF EXISTS "IconLibraryItems"               CASCADE;
 DROP TABLE IF EXISTS "DefectOrders"                   CASCADE;
 DROP TABLE IF EXISTS "SubmissionItems"                CASCADE;
 DROP TABLE IF EXISTS "ChecklistSubmissions"           CASCADE;
 DROP TABLE IF EXISTS "ChecklistTemplateItems"         CASCADE;
 DROP TABLE IF EXISTS "ChecklistTemplates"             CASCADE;
 DROP TABLE IF EXISTS "MachineAssignments"             CASCADE;
 DROP TABLE IF EXISTS "OperatorSupervisorAssignments"  CASCADE;
 DROP TABLE IF EXISTS "Machines"                       CASCADE;
 DROP TABLE IF EXISTS "AspNetUserTokens"               CASCADE;
 DROP TABLE IF EXISTS "AspNetUserRoles"                CASCADE;
 DROP TABLE IF EXISTS "AspNetUserLogins"               CASCADE;
 DROP TABLE IF EXISTS "AspNetUserClaims"               CASCADE;
 DROP TABLE IF EXISTS "AspNetRoleClaims"               CASCADE;
 DROP TABLE IF EXISTS "AspNetUsers"                    CASCADE;
 DROP TABLE IF EXISTS "AspNetRoles"                    CASCADE;
 DROP TABLE IF EXISTS "__EFMigrationsHistory"          CASCADE;

BEGIN;

-- ════════════════════════════════════════════════════════════════════════════
-- 1 · EF MIGRATIONS HISTORY
-- ════════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId"    character varying(150) NOT NULL,
    "ProductVersion" character varying(32)  NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- ════════════════════════════════════════════════════════════════════════════
-- 2 · ASP.NET IDENTITY TABLES
-- ════════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS "AspNetRoles" (
    "Id"               text NOT NULL,
    "Name"             character varying(256),
    "NormalizedName"   character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id"                   text NOT NULL,
    "FullName"             character varying(100) NOT NULL,
    "EmployeeNumber"       character varying(20)  NOT NULL,
    "Role"                 integer                NOT NULL DEFAULT 2,
    "IsActive"             boolean                NOT NULL DEFAULT TRUE,
    "CreatedAt"            timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UserName"             character varying(256),
    "NormalizedUserName"   character varying(256),
    "Email"                character varying(256),
    "NormalizedEmail"      character varying(256),
    "EmailConfirmed"       boolean                NOT NULL DEFAULT FALSE,
    "PasswordHash"         text,
    "SecurityStamp"        text,
    "ConcurrencyStamp"     text,
    "PhoneNumber"          text,
    "PhoneNumberConfirmed" boolean                NOT NULL DEFAULT FALSE,
    "TwoFactorEnabled"     boolean                NOT NULL DEFAULT FALSE,
    "LockoutEnd"           timestamp with time zone,
    "LockoutEnabled"       boolean                NOT NULL DEFAULT FALSE,
    "AccessFailedCount"    integer                NOT NULL DEFAULT 0,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId"     text NOT NULL,
    "ClaimType"  text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId"     text NOT NULL,
    "ClaimType"  text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider"       text NOT NULL,
    "ProviderKey"         text NOT NULL,
    "ProviderDisplayName" text,
    "UserId"              text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId"        text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name"          text NOT NULL,
    "Value"         text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "EmailIndex"                 ON "AspNetUsers"      ("NormalizedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex"       ON "AspNetUsers"      ("NormalizedUserName");
CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex"       ON "AspNetRoles"      ("NormalizedName");
CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId"  ON "AspNetUserRoles"  ("RoleId");

-- ════════════════════════════════════════════════════════════════════════════
-- 3 · DOMAIN TABLES
-- ════════════════════════════════════════════════════════════════════════════

-- 3.1 Machines  (includes TypeName added by 20260517000000_AddMachineTypeName)
CREATE TABLE IF NOT EXISTS "Machines" (
    "Id"                integer GENERATED BY DEFAULT AS IDENTITY,
    "MachineNumber"     character varying(50)  NOT NULL,
    "MachineName"       character varying(100) NOT NULL,
    "Type"              integer                NOT NULL DEFAULT 0,
    "TypeName"          character varying(100),
    "Description"       character varying(200),
    "IsActive"          boolean                NOT NULL DEFAULT TRUE,
    "IsImmobilised"     boolean                NOT NULL DEFAULT FALSE,
    "ImmobilisedReason" text,
    "CreatedAt"         timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT "PK_Machines" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Machines_MachineNumber" ON "Machines" ("MachineNumber");

-- 3.2 MachineAssignments  (includes MechanicId added by 20260325210000)
CREATE TABLE IF NOT EXISTS "MachineAssignments" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY,
    "MachineId"    integer                  NOT NULL,
    "OperatorId"   text                     NOT NULL,
    "MechanicId"   text,
    "AssignedFrom" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "AssignedTo"   timestamp with time zone,
    "IsActive"     boolean                  NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_MachineAssignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MachineAssignments_Machines_MachineId"
        FOREIGN KEY ("MachineId")  REFERENCES "Machines"    ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MachineAssignments_AspNetUsers_OperatorId"
        FOREIGN KEY ("OperatorId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    -- Mechanic FK has no cascade (mirrors migration 20260408103703_InitialCreate1)
    CONSTRAINT "FK_MachineAssignments_AspNetUsers_MechanicId"
        FOREIGN KEY ("MechanicId") REFERENCES "AspNetUsers" ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_MachineAssignments_MachineId"  ON "MachineAssignments" ("MachineId");
CREATE INDEX IF NOT EXISTS "IX_MachineAssignments_OperatorId" ON "MachineAssignments" ("OperatorId");
CREATE INDEX IF NOT EXISTS "IX_MachineAssignments_MechanicId" ON "MachineAssignments" ("MechanicId");

-- 3.3 OperatorSupervisorAssignments  (added by 20260325000000)
CREATE TABLE IF NOT EXISTS "OperatorSupervisorAssignments" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY,
    "OperatorId"   text                     NOT NULL,
    "SupervisorId" text                     NOT NULL,
    "AssignedAt"   timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "IsActive"     boolean                  NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_OperatorSupervisorAssignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OperatorSupervisorAssignments_AspNetUsers_OperatorId"
        FOREIGN KEY ("OperatorId")   REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OperatorSupervisorAssignments_AspNetUsers_SupervisorId"
        FOREIGN KEY ("SupervisorId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_OperatorSupervisorAssignments_OperatorId"   ON "OperatorSupervisorAssignments" ("OperatorId");
CREATE INDEX IF NOT EXISTS "IX_OperatorSupervisorAssignments_SupervisorId" ON "OperatorSupervisorAssignments" ("SupervisorId");

-- 3.4 ChecklistTemplates
CREATE TABLE IF NOT EXISTS "ChecklistTemplates" (
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY,
    "MachineType" integer                NOT NULL DEFAULT 0,
    "Name"        character varying(100) NOT NULL,
    "MachineId"   integer                NOT NULL,
    CONSTRAINT "PK_ChecklistTemplates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChecklistTemplates_Machines_MachineId"
        FOREIGN KEY ("MachineId") REFERENCES "Machines" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ChecklistTemplates_MachineId" ON "ChecklistTemplates" ("MachineId");

-- 3.5 ChecklistTemplateItems  (includes detail columns from 20260325200000)
CREATE TABLE IF NOT EXISTS "ChecklistTemplateItems" (
    "Id"               integer GENERATED BY DEFAULT AS IDENTITY,
    "TemplateId"       integer                NOT NULL,
    "ItemName"         character varying(200) NOT NULL,
    "Section"          character varying(50),
    "SortOrder"        integer                NOT NULL DEFAULT 0,
    "IsNoGoItem"       boolean                NOT NULL DEFAULT FALSE,
    "StatusLabel"      character varying(100),
    "Action"           character varying(1000),
    "InOrderCondition" character varying(1000),
    "DefectCondition"  character varying(1000),
    "IconPath"         character varying(500),
    CONSTRAINT "PK_ChecklistTemplateItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChecklistTemplateItems_ChecklistTemplates_TemplateId"
        FOREIGN KEY ("TemplateId") REFERENCES "ChecklistTemplates" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_ChecklistTemplateItems_TemplateId" ON "ChecklistTemplateItems" ("TemplateId");

-- 3.6 ChecklistSubmissions  (includes supervisor-workflow + signatures)
CREATE TABLE IF NOT EXISTS "ChecklistSubmissions" (
    "Id"                       integer GENERATED BY DEFAULT AS IDENTITY,
    "LocalId"                  uuid                     NOT NULL,
    "MachineId"                integer                  NOT NULL,
    "OperatorId"               text                     NOT NULL,
    "SupervisorId"             text,
    "MechanicId"               text,
    "Shift"                    integer                  NOT NULL DEFAULT 0,
    "SubmittedAt"              timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "KmOrHourMeter"            integer,
    "OperatorRemarks"          character varying(500),
    "FitnessDeclarationSigned" boolean                  NOT NULL DEFAULT FALSE,
    "Status"                   integer                  NOT NULL DEFAULT 0,
    "SupervisorSignedAt"       timestamp with time zone,
    "MechanicSignedAt"         timestamp with time zone,
    "MechanicNotes"            character varying(500),
    "RejectionReason"          character varying(500),
    "RejectedMechanicId"       text,
    "IsSyncedToCloud"          boolean                  NOT NULL DEFAULT TRUE,
    "OperatorSignature"        text,
    "SupervisorSignature"      text,
    CONSTRAINT "PK_ChecklistSubmissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChecklistSubmissions_Machines_MachineId"
        FOREIGN KEY ("MachineId")          REFERENCES "Machines"    ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ChecklistSubmissions_AspNetUsers_OperatorId"
        FOREIGN KEY ("OperatorId")         REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ChecklistSubmissions_AspNetUsers_SupervisorId"
        FOREIGN KEY ("SupervisorId")       REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_ChecklistSubmissions_AspNetUsers_MechanicId"
        FOREIGN KEY ("MechanicId")         REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_ChecklistSubmissions_AspNetUsers_RejectedMechanicId"
        FOREIGN KEY ("RejectedMechanicId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ChecklistSubmissions_LocalId"            ON "ChecklistSubmissions" ("LocalId");
CREATE INDEX IF NOT EXISTS "IX_ChecklistSubmissions_MachineId"                 ON "ChecklistSubmissions" ("MachineId");
CREATE INDEX IF NOT EXISTS "IX_ChecklistSubmissions_OperatorId"                ON "ChecklistSubmissions" ("OperatorId");
CREATE INDEX IF NOT EXISTS "IX_ChecklistSubmissions_SupervisorId"              ON "ChecklistSubmissions" ("SupervisorId");
CREATE INDEX IF NOT EXISTS "IX_ChecklistSubmissions_MechanicId"                ON "ChecklistSubmissions" ("MechanicId");
CREATE INDEX IF NOT EXISTS "IX_ChecklistSubmissions_RejectedMechanicId"        ON "ChecklistSubmissions" ("RejectedMechanicId");

-- 3.7 SubmissionItems
CREATE TABLE IF NOT EXISTS "SubmissionItems" (
    "Id"             integer GENERATED BY DEFAULT AS IDENTITY,
    "SubmissionId"   integer NOT NULL,
    "TemplateItemId" integer NOT NULL,
    "Status"         integer NOT NULL DEFAULT 1,
    "Notes"          character varying(500),
    CONSTRAINT "PK_SubmissionItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SubmissionItems_ChecklistSubmissions_SubmissionId"
        FOREIGN KEY ("SubmissionId")   REFERENCES "ChecklistSubmissions"   ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SubmissionItems_ChecklistTemplateItems_TemplateItemId"
        FOREIGN KEY ("TemplateItemId") REFERENCES "ChecklistTemplateItems" ("Id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_SubmissionItems_SubmissionId"   ON "SubmissionItems" ("SubmissionId");
CREATE INDEX IF NOT EXISTS "IX_SubmissionItems_TemplateItemId" ON "SubmissionItems" ("TemplateItemId");

-- 3.8 DefectOrders  (includes MechanicSignature from 20260519000000)
CREATE TABLE IF NOT EXISTS "DefectOrders" (
    "Id"                 integer GENERATED BY DEFAULT AS IDENTITY,
    "SubmissionId"       integer                  NOT NULL,
    "SubmissionItemId"   integer                  NOT NULL,
    "DefectDescription"  character varying(200)   NOT NULL,
    "PartRequired"       character varying(200),
    "PartNumber"         character varying(50),
    "RepairStatus"       integer                  NOT NULL DEFAULT 0,
    "AssignedMechanicId" text,
    "CreatedAt"          timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "ResolvedAt"         timestamp with time zone,
    "ResolutionNotes"    character varying(500),
    "MechanicSignature"  text,
    CONSTRAINT "PK_DefectOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DefectOrders_ChecklistSubmissions_SubmissionId"
        FOREIGN KEY ("SubmissionId")       REFERENCES "ChecklistSubmissions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DefectOrders_SubmissionItems_SubmissionItemId"
        FOREIGN KEY ("SubmissionItemId")   REFERENCES "SubmissionItems"      ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DefectOrders_AspNetUsers_AssignedMechanicId"
        FOREIGN KEY ("AssignedMechanicId") REFERENCES "AspNetUsers"          ("Id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "IX_DefectOrders_SubmissionId"       ON "DefectOrders" ("SubmissionId");
CREATE INDEX IF NOT EXISTS "IX_DefectOrders_SubmissionItemId"   ON "DefectOrders" ("SubmissionItemId");
CREATE INDEX IF NOT EXISTS "IX_DefectOrders_AssignedMechanicId" ON "DefectOrders" ("AssignedMechanicId");

-- 3.9 IconLibraryItems  (added by 20260520000000)
CREATE TABLE IF NOT EXISTS "IconLibraryItems" (
    "Id"               integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"             character varying(120) NOT NULL,
    "OriginalFileName" character varying(255) NOT NULL,
    "FilePath"         character varying(255) NOT NULL,
    "ContentType"      character varying(80),
    "FileSize"         bigint                 NOT NULL DEFAULT 0,
    "UploadedAt"       timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UploadedById"     character varying(450),
    CONSTRAINT "PK_IconLibraryItems" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_IconLibraryItems_Name" ON "IconLibraryItems" ("Name");

-- ════════════════════════════════════════════════════════════════════════════
-- 4 · SEED · IDENTITY ROLES
--      (matches Program.cs roleManager.CreateAsync calls)
-- ════════════════════════════════════════════════════════════════════════════
INSERT INTO "AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp")
VALUES
    ('11111111-1111-1111-1111-111111111111', 'Admin',      'ADMIN',      gen_random_uuid()::text),
    ('22222222-2222-2222-2222-222222222222', 'Operator',   'OPERATOR',   gen_random_uuid()::text),
    ('33333333-3333-3333-3333-333333333333', 'Supervisor', 'SUPERVISOR', gen_random_uuid()::text),
    ('44444444-4444-4444-4444-444444444444', 'Mechanic',   'MECHANIC',   gen_random_uuid()::text)
ON CONFLICT ("Id") DO NOTHING;

-- ════════════════════════════════════════════════════════════════════════════
-- 5 · SEED · DEFAULT ADMIN USER
--   Email    : admin@belfast.co.za
--   Password : Admin@123          (HASHED below — change immediately after login)
--
--   The hash was produced by ASP.NET Identity v3 (PBKDF2-HMAC-SHA256, 10 000 iter.)
--   for the password 'Admin@123'. If you want to use a different password,
--   either:
--     a) leave this hash in place, log in, then change your password via the UI; OR
--     b) start the app first — Program.cs auto-creates this user on first run
--        with the default password if it doesn't exist — and skip this section.
-- ════════════════════════════════════════════════════════════════════════════
INSERT INTO "AspNetUsers" (
    "Id", "FullName", "EmployeeNumber", "Role", "IsActive", "CreatedAt",
    "UserName", "NormalizedUserName", "Email", "NormalizedEmail",
    "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp",
    "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnabled", "AccessFailedCount"
) VALUES (
    '00000000-0000-0000-0000-000000000001',
    'System Administrator',
    'ADMIN001',
    1,                              -- UserRole.Admin
    TRUE,
    (now() AT TIME ZONE 'utc'),
    'admin@belfast.co.za',
    'ADMIN@BELFAST.CO.ZA',
    'admin@belfast.co.za',
    'ADMIN@BELFAST.CO.ZA',
    TRUE,
    -- PBKDF2 hash of 'Admin@123'
    'AQAAAAIAAYagAAAAEFv8WqsuG3W7G2bM4d2BjEsAJoq6f3Yh5h0sQpJv4HnPmGB0nUbWf2eRBpW7zR3v9w==',
    gen_random_uuid()::text,
    gen_random_uuid()::text,
    FALSE, FALSE, TRUE, 0
)
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "AspNetUserRoles" ("UserId", "RoleId")
VALUES (
    '00000000-0000-0000-0000-000000000001',
    '11111111-1111-1111-1111-111111111111'
)
ON CONFLICT DO NOTHING;

-- ════════════════════════════════════════════════════════════════════════════
-- 6 · MARK ALL MIGRATIONS AS APPLIED
--      So `dotnet ef database update` reports "no pending migrations" instead
--      of trying to re-run them against the already-built schema.
-- ════════════════════════════════════════════════════════════════════════════
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES
    ('20260312074136_InitialCreate',                  '8.0.0'),
    ('20260325000000_AddSupervisorWorkflow',          '8.0.0'),
    ('20260325200000_AddTemplateItemDetails',         '8.0.0'),
    ('20260325210000_AddMechanicToMachineAssignment', '8.0.0'),
    ('20260408103703_InitialCreate1',                 '8.0.0'),
    ('20260517000000_AddMachineTypeName',             '8.0.0'),
    ('20260519000000_AddDigitalSignatures',           '8.0.0'),
    ('20260520000000_AddIconLibrary',                 '8.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;

-- ════════════════════════════════════════════════════════════════════════════
-- ✓ Done.
--   Next steps:
--     1. Update appsettings.json → ConnectionStrings:DefaultConnection
--        to point at this database.
--     2. Run the app (`dotnet run`) — it should start without trying to apply
--        any migrations.
--     3. Sign in with admin@belfast.co.za / Admin@123 and change the password
--        from the user menu.
-- ════════════════════════════════════════════════════════════════════════════
